#!/usr/bin/env ruby

# setting
album = 'gyazogle'
maxSize = 2048

require 'net/http'
require 'fileutils'

# capture png file
tmpfile = "/tmp/image_#{Time.new.strftime("%Y%m%d%H%M%S")}.png"
imagefile = ARGV[1]

if imagefile && File.exist?(imagefile) then
  FileUtils.cp(imagefile, tmpfile)
else
  system "screencapture -i \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    system "sips -d profile --deleteColorManagementProperties \"#{tmpfile}\""
    dpiWidth    = `sips -g dpiWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    dpiHeight   = `sips -g dpiHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelWidth  = `sips -g pixelWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelHeight = `sips -g pixelHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    if (dpiWidth.to_f > 72.0 and dpiHeight.to_f > 72.0) then
        width  =  pixelWidth.to_f * 72.0 / dpiWidth.to_f
        height =  pixelHeight.to_f* 72.0 / dpiHeight.to_f
        system "sips -s dpiWidth 72 -s dpiHeight 72 -z #{height} -s formatOptions best #{width} \"#{tmpfile}\""
    end
  end
end

if !File.exist?(tmpfile) then
  exit
end

# resize
pixelWidth  = `sips -g pixelWidth "#{tmpfile}" | awk '/:/ {print $2}'`.to_i
pixelHeight = `sips -g pixelHeight "#{tmpfile}" | awk '/:/ {print $2}'`.to_i
if (maxSize < pixelWidth or maxSize < pixelHeight) then
  system "sips -Z #{maxSize} -s formatOptions best \"#{tmpfile}\""
end

# upload
`/usr/local/bin/google picasa post --title '#{album}' #{tmpfile}`
url = `/usr/local/bin/google picasa list --fields url-direct --title '#{album}' | grep '#{File.basename(tmpfile)}'`.chomp
#url = `/usr/local/bin/google picasa list --fields url-direct --title '#{album}' --query '#{File.basename(tmpfile)}'`.chomp

# get original size url
url = url.sub(File.basename(tmpfile), "s#{maxSize}/#{File.basename(tmpfile)}")

IO.popen("pbcopy","r+"){|io|
  io.write url
  io.close
}
system "open #{url}"

File.delete(tmpfile)

